from pydantic import BaseModel , Field

class ClarifyWithUser(BaseModel):
    need_clarification: bool = Field(
        description="Whether additional user input is required before research can begin."
    )

    clarification_question: str | None = Field(
        default=None,
        description="A single concise question to resolve the ambiguity. Leave null when no clarification is needed."
    )

    reasoning: str = Field(
        description="Brief explanation for the decision. Used for debugging and evaluation."
    )
class ResearchBrief(BaseModel):
    """Structured research brief generated by the Planner."""
    research_brief : str 