from pydantic import BaseModel

class ClarifyWithUser(BaseModel):
    """Planner requests more information from the user."""
    need_clarification : bool
    clarification_question : str | None = None
    
class ResearchBrief(BaseModel):
    """Structured research brief generated by the Planner."""
    research_brief : str 